security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        admin_users:
            memory:
                users:
                    johndoe@mailinator.com:
                        password: '$2y$13$.oaFkWoNsnlqjifcLQXXyul8V/3lzR4D7SbfjiEpS1tPAeXm/wQZO' # Admin@123546
                        roles: [ 'ROLE_USER', 'ROLE_ADMIN' ]
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider 
        admin:
            pattern: ^/
            provider: admin_users
            custom_authenticator: App\Security\AdminAuthenticator
            logout:
                path: app_logout
                target: app_home
        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            entry_point: App\Security\CustomEntryPoint
            jwt: ~
            refresh_jwt:
                check_path: /api/token/refresh
            json_login:
                check_path: /api/login_check
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
    
    
    
    
    access_control:
       - { path: ^/admin, roles: ROLE_ADMIN }
       - { path: ^/api/login_check, roles: PUBLIC_ACCESS }
       - { path: ^/api/token/refresh, roles: PUBLIC_ACCESS }
    # - { path: ^/profile, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
