vich_uploader:
    db_driver: orm
    mappings:
        profile:
            uri_prefix: /images/users
            upload_destination: '%kernel.project_dir%/public/images/profile'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
